development:
  adapter: postgresql
  database: fith_evaluation_development
  username: dev
  password: dev

test:
  adapter: postgresql
  database: fith_evaluation_test
  username: dev
  password: dev

production:
  adapter: postgresql
  database: fith_evaluation_production
  username: dev
  password: dev
