source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
gem 'devise'
gem 'sqlite3'
gem 'pg'
gem 'carrierwave'
gem 'pry'
gem 'factory_girl'
gem 'rack-test'
# Use SCSS for stylesheets
gem 'haml'

gem 'bcrypt-ruby', '~> 3.0.0'
gem 'pry'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
gem 'omniauth-twitter', :git => 'https://github.com/arunagw/omniauth-twitter.git'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'
gem 'searcher', git: 'git://github.com/Stial08/searcher'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :assets do
  gem 'sass-rails', '~> 4.0.0'
end

group :test, :development do
  gem 'rspec-rails', "~> 2.14.0"
end

group :test do
  gem 'capybara', "~> 2.1.0"
end
